FROM pytorch/pytorch:1.0-cuda10.0-cudnn7-runtime

RUN apt-get update && apt-get install -y git

RUN git clone https://github.com/YBIGTA/pytorch-hair-segmentation.git

WORKDIR /pytorch-hair-segmentation

RUN pip install -r requirements.txt

RUN sh data/figaro.sh

RUN python -m visdom.server